#!/bin/bash
#
# sbox
# Sandbox instance management.
#
# Copyright: 2019 Shawwwn, shawwwn1@gmail.com
# License: MIT
#
# Usage: sbox-mgt ACTION [ARGS...] [OPTION]
#

function help {
	local executable=$(basename $0)
	echo "usage: $executable stop [-n NAME|-c|-m|-v]"
	echo "       $executable join [-n NAME|-v]"
	echo "       $executable list [-n NAME|-a|-v]"
	echo "       $executable [-h|--help]"
	echo "Sandbox instance management."
	echo ""
	echo "	stop:"
	echo "		Kill the sandbox'ed process."
	echo "		Specify whether to commit/merge changes with flags -c/-m."
	echo ""
	echo "	join:"
	echo "		Send process into a running container."
	echo ""
	echo "	list:"
	echo "		List *running* containers. Use with -v for more details."
	echo ""
	echo "	remove:"
	echo "		Remove an inactive container."
	echo ""
	echo "	-n, --container-name             Name of the target sandbox."
	echo "	-c, --auto-commit                Auto commit file system changes"
	echo "	                                 to snapshot when exit"
	echo "	-m, --auto-merge                 Auto merge snapshot to rootfs"
	echo "	                                 when exit."
	echo "	-a, --list-all                   List all containers, including"
	echo "	                                 ones that are not running."
	echo "	-v, --verbose                    Print more infomation."
	echo "	-h, --help                       Display this help and exit."
}

# process command line arguments
VERBOSE=false
AUTO_COMMIT=false
AUTO_MERGE=false
LIST_ALL=false
CONTAINER_NAME="default"
SET_NAME=false
ARGS=$(getopt -q \
	-o "n:cmavh" \
	-l "container-name:,auto-commit,auto-merge,list-all,verbose,help" \
	-n "sbox-mgt" -- "$@")
if [ $? -ne 0 ]; then
	echo "Invalid Arguments!"
	exit 2
fi

eval set -- "$ARGS"
while true; do
	case "$1" in
		-n|--container-name)
			CONTAINER_NAME="$2"
			SET_NAME=true
			shift 2 ;;
		-c|--auto-commit)
			AUTO_COMMIT=true
			shift ;;
		-m|--auto-merge)
			AUTO_MERGE=true
			shift ;;
		-a|--list-all)
			LIST_ALL=true
			shift ;;
		-v|--verbose)
			VERBOSE=true 
			shift ;;
		-h|--help)
			help
			shift
			exit ;;
		--)
			shift
			break ;;
	esac
done

# globals
CMD=$(echo "$1" | awk '{print tolower($0)}')
shift


#############################################################
# Get the nth parent pid, start from given pid
#############################################################
get_nth_ppid() {
	local pid=$1
	local n=$2

	local ppid=$(ps --no-headers -o ppid "$pid" | xargs) # trim result from 'ps'
	[ -z n ] && n=1
	[ $n -eq 0 ] && echo "$pid" && return

	if (( $n > 1 )); then
		get_nth_ppid "$ppid" $((n-1))
	else
		echo "$ppid"
	fi
}

#############################################################
# Set pid's environment variable
#############################################################
set_pid_env() {
	local pid=$1
	local var=$2
	local val="$3"

	if [ -z "$3" ]; then
		# unset $var
		gdb -n -q -p $pid <<<"""
			call (int) unsetenv(\"$var\")
			set confirm off
			quit
		""" >/dev/null
	else
		# set $var
		gdb -n -q -p $pid <<<"""
			call (int) setenv(\"$var\", \"$val\")
			set confirm off
			quit
		""" >/dev/null
	fi
}

#############################################################
# Trying to terminate a process nicely
#############################################################
kill_proc_nice() {
	local pid=$1
	if ! ps -p $pid >/dev/null; then return 0; fi

	local killed=false
	local i=0

	kill -SIGINT $pid
	for ((i=0; i<20; i++)); do # 2s timeout
		if ! ps -p $pid >/dev/null; then
			killed=true
			break
		fi
		sleep 0.1
	done
	if $killed; then return 0; fi

	kill -SIGTERM $pid
	for ((i=0; i<30; i++)); do # 3s timeout
		if ! ps -p $pid >/dev/null; then
			killed=true
			break
		fi
		sleep 0.1
	done
	if $killed; then return 0; fi

	kill -SIGKILL $pid
}

#############################################################
# Trying to terminate a process tree nicely
#############################################################
kill_tree_nice() {
	local pid=$1

	for child in $(ps -o "pid" --no-headers --ppid $pid); do
		kill_tree_nice $child
	done

	kill_proc_nice $pid
}

#############################################################
# Return container pid if running
#############################################################
get_container_pid() {
	local name="$1"
	local pid=$(cat "/tmp/sbox/$name/container.pid" 2>/dev/null)
	if [ ! -z "$pid" ] && (ps -p "$pid" >/dev/null 2>&1); then
		echo "$pid"
		return 0
	fi
	return 1;
}

#############################################################
# Print error message & exit
#############################################################
error_exit() {
	echo -e "$1" >&2
	exit 1
}

#############################################################
# Return a list of containers under base directory
#############################################################
list_containers() {
	local base_dir=$(realpath "$1") # /tmp/sbox

	pushd "$base_dir" >/dev/null
	local name
	find * -maxdepth 0 -type d | \
		while IFS= read -r name; do
			if [ -f "$base_dir/$name/config" ]; then
				echo "$name"
			fi
		done
	popd >/dev/null
}

#############################################################
# Return a list of containers under base directory
#############################################################
show_container_info() {
	local name="$1"

	if get_container_pid "$CONTAINER_NAME" >/dev/null; then
		echo -e "\e[32m$1\e[0m" # active container, print in green
	else
		echo -e "\e[31m$1\e[0m" # inactive container, print in red
	fi

	# source configuration file in a subshell
	$VERBOSE && {
		source "/tmp/sbox/$CONTAINER_NAME/config"
		echo "snapshot_dir=$SBOX_SNAPSHOT_DIR"
		echo "dirty_dir=$SBOX_DIRTY_DIR"
		echo "rootfs=$SBOX_ROOTFS"
		echo "mapped_user=$SBOX_USER"
		echo "exec=$SBOX_EXEC"
		echo "ppid=$SBOX_PID"
		echo "pid=$SBOX_PPID"
	}
}



# main()
spid=$(get_container_pid "$CONTAINER_NAME") # pid of sandbox'ed program
$SET_NAME && $VERBOSE && echo "container name: $CONTAINER_NAME"

if [ "$CMD" = "stop" ]; then
	$VERBOSE && echo "container pid: $spid"
	[ -z $spid ] && error_exit "Container \"$CONTAINER_NAME\" is not running."

	cpid=$(get_nth_ppid $spid 3) # container pid

	# set target process' environment variable
	set_pid_env $cpid AUTO_COMMIT "$AUTO_COMMIT"
	set_pid_env $cpid AUTO_MERGE "$AUTO_MERGE"

	# kill target process
	kill_tree_nice $spid

elif [ "$CMD" = "join" ]; then
	$VERBOSE && echo "container pid: $spid"
	[ -z $spid ] && error_exit "Container \"$CONTAINER_NAME\" is not running."
	KILLED=false

	# launch process inside namespace
	echo "Joining container \"$CONTAINER_NAME\":"
	nsenter -a -t $spid --no-fork \
	bash -c """$(cat <<-EOF
		ppid=\$(cat /proc/self/status | grep ^PPid: | awk '{print \$2}')
		cd "/tmp/sbox/$CONTAINER_NAME"
		exec chroot rootfs \
			sudo -u $USER \
				bash -c 'cd ~; exec $@'
		EOF
	)"""
	[ $? == 137 ] && KILLED=true

	# fix shell's strange behavior after sandbox's main process was killed(-9) 
	# thus bringing down joint process
	if $KILLED; then
		echo "sandbox is being torn down, exiting ..."
		stty sane
		# $KILLED && kill -9 $$ 
	fi

elif [ "$CMD" = "list" ]; then
	if $SET_NAME; then
		show_container_info "$CONTAINER_NAME"
	else
		# traverse containers
		list_containers "/tmp/sbox" | while IFS= read -r CONTAINER_NAME; do
			# filter if needed
			if ! ($LIST_ALL || get_container_pid "$CONTAINER_NAME" >/dev/null); then
				continue
			fi
			show_container_info "$CONTAINER_NAME"
		done
	fi

else
	help

fi

